import { Component, } from '@angular/core';
import { NavController } from 'ionic-angular';
import { Injectable, Pipe, PipeTransform } from '@angular/core';
import { Modal, ModalController, ModalOptions } from 'ionic-angular';
import { Validators, FormBuilder, FormGroup } from '@angular/forms';

@Component({
  selector: 'page-home',
  templateUrl: 'home.html'
})

export class HomePage {
  public form: FormGroup;
  names: Array<any>;
  toDos: string[] = ["Todo1", "Todo2", "Todo3"];
  heroes = ['Windstorm', 'Bombasto', 'Magneta', 'Tornado'];
  public employees = ['17-OH-Progesterone',
  'A/G (Tỷ số Albumin/Globulin)',
  'Acetaminophen',
  'Acetyl Cholinesterase (CHE)',
  'Acid Phosphatase',
  'Acid Uric (Blood/Urine)',
  'ACTH ',
  'Active Renin',
  'ADA (Adenosine Deaminase)',
  'Adeno Virus IgG',
  'Adeno Virus IgM',
  'ADH (Anti Diuretic Hormone)',
  'AFP (Alpha - Fetoprotein)',
  'ALA/Urine (Amino Levulinic Acid)',
  'Albumin',
  'Aldosterone',
  'Alkaline Phosphatase (ALP)',
  'Allergy Panel (Bộ dị ứng)',
  'Alpha 1 Antitrypsine',
  'Alpha 2 - Macrolobulin',
  'Alpha TNF (Tumor Necrosis Factor)',
  'ALT / SGPT ',
  'AMA-M2 (Antimitochondrial Ab)',
  'AMH (Anti-Mullerian Hormon)',
  'Amibe/Blood',
  'Amibe/Stool',
  'Amikacin/75',
  'Amoniac - NH3 Blood/Urine',
  'Amphetamin/Urine (test)',
  'Amphetamin/Urine (định lượng)',
  'Amylase (Blood/Urine)',
  'ANA Test (Anti Nuclear Ab)',
  'ANCA Screen (Anti Neutrophil Cytoplasmic Ab)',
  'Androstenedione',
  'Angiostrongylus Cantonensis IgG',
  'Angiostrongylus Cantonensis IgM',
  'Anti Beta2 Glycoprotein IgG',
  'Anti Beta2 Glycoprotein IgM',
  'Anti Cardiolipin IgG',
  'Anti Cardiolipin IgM',
  'Anti CCP ',
  'Anti HAV IgM',
  'Anti HAV Total',
  'Anti HBc Total ',
  'Anti HBc-IgM',
  'Anti HBe',
  'Anti HBs (Đ.lượng, quantitative)',
  'Anti HDV-IgG',
  'Anti HDV-IgM',
  'ANTI HEV-IgG',
  'ANTI HEV-IgM',
  'Anti Mycoplasma Pneumoniae-IgG',
  'Anti Mycoplasma Pneumoniae-IgM',
  'Anti Nucleosome',
  'Anti Phospholipid IgG',
  'Anti Phospholipid IgM',
  'Anti Thrombin III',
  'Anti Thyroglobulin (Anti TG)',
  'Anti TPO (Anti Microsomal) ',
  'Anti-C1q',
  'Anti-Centromer B',
  'Anti-dsDNA (Anti double strand DNA)',
  'Anti-GAD (Glutamic Acid Decarboxylase)',
  'Anti-Histone',
  'Anti-Jo-1',
  'Anti-LKM-1',
  'Anti-RNP-70 (RiboNucleoProtein)',
  'Anti-RNP-Sm',
  'Anti-Scl-70',
  'Anti-Sm',
  'Anti-SS-A',
  'Anti-SS-B',
  'APO Lipoprotein-A1',
  'APO Lipoprotein-B',
  'APTT / TCK',
  'Ascaris lumbricoides IgG',
  'Ascaris lumbricoides IgM',
  'ASO (Quantitative)',
  'Aspergillus-IgG',
  'Aspergillus-IgM',
  'AST / SGOT ',
  'B12 (Vit B12)',
  'Barbiturate/Urine',
  'Benzodiazepine/Urine',
  'Beta 2 Microglobulin ',
  'Beta CrossLaps',
  'Bicarbonat (HCO3)',
  'Bilirubin D',
  'Bilirubin T',
  'BK (TB IgG/IgM)',
  'BK (Tuberculosis) Culture (Cấy + KSĐ)',
  'BK (Tuberculosis) PCR',
  'BK (Tuberculosis)(AFB) nhuộm, soi KHV',
  'Bleeding time & Coagulation time (TS - TC )',
  'Blood gages - khí máu (A.B.G)',
  'C3',
  'C4',
  'CA 125 ',
  'CA 15-3',
  'CA 19-9',
  'CA 72-4 ',
  'Ca Total',
  'Calcitonin (hCT)',
  'Cặn ADDIS ',
  'Candida-IgG',
  'Candida-IgM',
  'Cannabinoids II',
  'Catecholamines (Adrenalin/Noradrenalin/Dopamine)',
  'Cấy + KSĐ',
  'Cấy máu + KSĐ (Blood Culture)',
  'Cấy nấm + KSĐ (Fungus Culture)',
  'Cấy phân + KSĐ (Stool Culture)',
  'CEA ',
  'Ceruloplasmine',
  'Ceton/Blood',
  'Chì máu (Plomb/Lead)',
  'Chì nước tiểu (ALA/urine)',
  'Chlamydia Pneumoniae-IgG',
  'Chlamydia Pneumoniae-IgM',
  'Chlamydia Trachomatis - DNA',
  'Chlamydia Trachomatis Ag',
  'Chlamydia Trachomatis IgG',
  'Chlamydia Trachomatis IgM',
  'Cholesterol Total',
  'CK-MB ',
  'Clonorchis Sinensis IgG',
  'Clonorchis Sinensis IgM',
  'CMV DNA (Realtime - Đ.lượng)',
  'CMV IgG',
  'CMV IgM ',
  'Cocain Metabolic',
  'Công thức máu/Huyết đồ (CBC)',
  'Copeptin',
  'Cortisol (Blood/Urine)',
  'C-Peptid ',
  'CPK',
  'Creatinin (Blood/Urine)',
  'Creatininine Clearance',
  'CRP hs',
  'CRP Total',
  'Cyclosporine ',
  'Cyfra 21-1',
  'Cystatin C',
  'Cysticercose IgG',
  'Cysticercose IgM',
  'D.Dimer ',
  'Dengue Fever-IgG/IgM',
  'Dengue NS1 Ag ',
  'DHEA SO4',
  'Diazepam/Urine',
  'Điện di Hb',
  'Điện di Protein/Máu',
  'Điện di Protein/Nước tiểu',
  'Điện giải đồ (Na+, K+, Ca++)',
  'Điện giải đồ (Na+, K+, CL -)',
  'Digitoxin',
  'Digoxin',
  'Độ lọc cầu thận (eGFR)',
  'Đồng (Copper/Cu)',
  'Đột biến EGFR (EGFR Mutant)',
  'Đột biến gen ung thư vú và buồng trứng (BRCA1, BRCA2, CHEK2)',
  'Double test (PAPP-A, Free Beta HCG)',
  'Drug of Abuse Screen Urine (bộ chẩn đoán thuốc gây nghiện MOP/MDMA/MET/THC)',
  'EA IgG',
  'EBNA IgG (Epstein Barr nuclear antigen)',
  'EBV DNA Realtime',
  'EBV-IgG',
  'EBV-IgM',
  'EBV - VCA  IgA',
  'EBV - VCA  IgG',
  'EBV - VCA  IgM',
  'Echinococcus IgG',
  'Echinococcus IgM ',
  'ENA - Plus (Sceening)',
  'Enterovirus IgG',
  'Enterovirus IgM',
  'Erythropoietin (EPO) Định lượng',
  'Estradiol (E2)',
  'ETOH (Cồn/máu)',
  'EV71 PCR (Bệnh tay chân miệng)',
  'EV71 test (Bệnh tay chân miệng)',
  'Everolimus',
  'Factor V Layden',
  'Fasciola Hepatica/Blood',
  'Ferritin',
  'Fibrinogen ',
  'Filariasis/Blood',
  'FOB (Fecal Occult Blood)',
  'Folate',
  'Free Metanepharine/Blood',
  'Free PSA',
  'Free T3 ',
  'Free T4',
  'Fructosamine ',
  'FSH',
  'G6 - PD',
  'Gamma Interferon',
  'Galectin',
  'Gastrin',
  'Gentamicin',
  'Giải phẫu bệnh - Mô bệnh học',
  'Giải phẫu bệnh - Tế bào',
  'GGT',
  'Globulin',
  'Glucose ',
  'Gnathostoma IgG',
  'Gonorrhea Ag',
  'Haptoglobin',
  'HbA1c',
  'HBeAg',
  'HBeAg Định lượng',
  'HBsAg (Đ.tính, qualitative)',
  'HBsAg Định lượng',
  'HBV DNA Realtime (Đ.lượng)',
  'HBV Genotype ',
  'HCC risk (AFP, AFP-L3, PIVKA II)',
  'HCG Beta (Blood)',
  'HCG/Urine (Đ.lượng)',
  'HCG/Urine (Đ.tính)',
  'HCV Ab',
  'HCV Ag ',
  'HCV Genotype ',
  'HCV RNA Realtime (Đ.lượng)',
  'HDL Cholesterol',
  'HDV Ag',
  'HE 4 (Human Epididymal Protein 4)',
  'Heroin, Morphin/Blood ',
  'Heroin,Morphin/Urine',
  'hGH (human Growth Hormone)',
  'HIV Ag/Ab Combo',
  'HLA B27 định tính',
  'HLA B27 định type',
  'Homocysteine Total',
  'Hồng cầu lưới (Reticulocyte)',
  'HP Ab /Blood',
  'HP Test-IgG',
  'HP Test-IgM',
  'HP-Ag/Stool (EIA)',
  'HPV - Genotype',
  'HSV 1 IgG',
  'HSV 1/2 IgG',
  'HSV 1/2 IgM',
  'HSV 2 IgG',
  'HSV DNA 1,2 REALTIME',
  'ICA (Islet Cell Autoantibody)',
  'IFN (Interferon Gamma)',
  'IgA',
  'IgE Total',
  'IGF-1',
  'IgG',
  'IgM ',
  'IL 17A',
  'Infectious Mononucleosis',
  'Influenza A & B Ag',
  'Influenza Ag A / B / A(H1N1) ',
  'Insulin ',
  'Interleukin 2',
  'Interleukin 6',
  'Japanese Encephalitis-IgG',
  'Japanese Encephalitis-IgM',
  'Kappa',
  'Kẽm (ZINC)',
  'Keton/Urine',
  'Ketone/Blood ',
  'KST Sốt rét (Malaria Antigen P.f, P.v/Blood)',
  'KST Sốt rét (Malaria) Phết lam máu',
  'L 28B',
  'LA (Lupus Anticoagulant)',
  'Lactic Acid (Lactate)',
  'Lambda',
  'LDH Blood',
  'LDL Cholesterol',
  'LE CELLS',
  'Legionella Pneumophila IgG',
  'Legionella Pneumophila IgM',
  'Leptin',
  'Leptospira-IgG',
  'Leptospira-IgM',
  'LH',
  'Lipase/Blood',
  'Lipoprotein (a) Latex',
  'Magnesium (Blood/Urine) ',
  'Marijuana (cannabinoids)/Urine',
  'Máu lắng (ESR,VS)',
  'Melanine/Blood',
  'Melatonin/Saliva',
  'Metanephrine/Blood',
  'Methadone',
  'Methamphetamine Test/Urine',
  'Micro Albumin/Urine ',
  'Mumps IgG',
  'Mumps IgM',
  'Myoglobin',
  'Napa',
  'Neisseria Gonorrhoeae DNA',
  'NGAL (Neutrophil Gelactinase Associated Lipocalin)',
  'Nhiễm sắc thể đồ',
  'Nhóm máu (Blood Group ABO + Rh)',
  'Nhuộm Gram (Gram Stain)',
  'Normetanephrine',
  'NP dung nạp đường (Oral Glucose Tolerance Test)',
  'NSE (Neuron-Specific Enolase)',
  'NT - ProBNP II',
  'Opiates',
  'Osteocalcin',
  'P1NP Total',
  'Pancreatic Amylase',
  'Pap Smear (Tầm soát sớm ung thư cổ tử cung)',
  'Pap ThinPrep (USA)',
  'Pepsinogen1-2',
  'Phân tích mức độ đứt gẫy gen của tinh trùng (Halosperm)',
  'Phân tích sỏi (Stone Analyse : Kidney, Ureter,...) ',
  'Phencyclidine Plus',
  'Phenobarbital Cobas',
  'Phosphatase Acid/Blood',
  'Phosphatase kiềm',
  'Phospholipid',
  'Phosphorus (PO4)',
  'PIGF',
  'Pre Albumin',
  'Pro GRP (Pro Gastrin Releasing Peptide)',
  'Procalcitonin (PCT) ',
  'Procanamide',
  'Progesterone',
  'Prolactine',
  'Propoxyphene',
  'Protein Bence Jones',
  'Protein C',
  'Protein S',
  'Protein Total (Máu/Urine/CFS)',
  'PSA',
  'PT / TQ',
  'PTH',
  'Quinidine',
  'R.P.R (Rapid Plasma Reagin) / VDRL',
  'Reserve Alk (Dự trữ kiềm)',
  'RF (Quantitative)',
  'ROMA Test',
  'Rotavirus/Stool',
  'Rubella IgG',
  'Rubella IgM ',
  'S 100',
  'Salicylate',
  'Sán lá phổi (Paragonimus IgG)',
  'Sàng lọc sơ sinh 3 bệnh (G6PD, CH, CAH)',
  'Sàng lọc sơ sinh 5 bệnh (G6PD, CH, CAH,PKU, GALT)',
  'Sắt (Fe, Iron)',
  'SCC',
  'Schistosoma Mansoni IgG',
  'Sero Amibe',
  'Sero Fasciola Hepatica',
  'Sero Filariasis Ag',
  'sFlt-1',
  'SHBG ',
  'SLE ( Systemic Lupus Erythematosus )',
  'Sởi (Measles-IgG)',
  'Sởi (Measles-IgM)',
  'Soi tươi huyết trắng (nấm, KST, tạp trùng, tế bào thượng bì, hồng cầu, bạch cầu)',
  'Soi tươi dịch',
  'Soi tươi phân (Stool Exam)',
  'Soi tươi tìm nấm (Fungus Exam)',
  'sTfR ',
  'Streptococcus A Ag',
  'Strongyloides stercoralis IgG',
  'T3',
  'T4',
  'Tacrolimus ',
  'Taenia (Cysticercose - IgG)',
  'Testosterone ',
  'TG - Thyroglobulin',
  'Theophylline',
  'Thrombin Time (TT)',
  'TIBC / UIBC',
  'Tinh dịch đồ (SEMEN ANALYSIS)',
  'Tobramycin ',
  'Tổng phân tích nước tiểu (Urinary Analysis)',
  'Toxocara IgG',
  'Toxoplasma Gondii IgG ',
  'Toxoplasma Gondii IgM ',
  'TPHA/Syphilis ',
  'Transferrin',
  'Trichinella Spiralis IgG',
  'Trichinella Spiralis IgM',
  'Triglycerides',
  'Triple Test (AFP, HCG, uE3)',
  'Troponin-I',
  'Troponin-T, hs ',
  'Tryptase (TPS)',
  'TSH',
  'TSH Receptor (TRAb)',
  'Urea / BUN',
  'Vitamin D Total',
  'VLDL Cholesterol',
  'VZV DNA REALTIME',
  'VZV IgG',
  'VZV IgM',
  'Waaler Rose',
  'Widal Test',
  ]

  constructor(public navCtrl: NavController, private fb: FormBuilder, private modal: ModalController) {
    this.names = [{ Name: 'item-1', Value: false, deleted: false },
    { Name: 'item-2', Value: false, deleted: false }];
    this.form = fb.group({
      country: ["", Validators.required]
    });
  };
  delete(item) {
    item.deleted = true
    this.names = this.names.filter(it => it['deleted'] == false)
  };
  add() {
    console.log("function called");
    let current_length = this.names.length + 1
    this.names.push({ Name: 'item-' + current_length, Value: current_length, deleted: false })
  };
  onChange(item) {
    console.log(item.title)
  }
  openModal() {

    const myModalOptions: ModalOptions = {
      enableBackdropDismiss: false
    };

    const myModalData = {
      name: 'Paul Halliday',
      occupation: 'Developer'
    };

    const myModal: Modal = this.modal.create('ModalPage', { data: myModalData }, myModalOptions);

    myModal.present();

    myModal.onDidDismiss((data) => {
      console.log("I have dismissed.");
      console.log(data);
    });

    myModal.onWillDismiss((data) => {
      console.log("I'm about to dismiss");
      console.log(data);
    });

  }
}

